---
name: test

'on':
  pull_request:
  push:
    branches:
      - main

# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        clojure: ['1.10.1.739']
        elixir: ['1.11.x']
        erlang: ['22.x', '23.x']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.erlang }}
      - uses: DeLaGuardo/setup-clojure@3.1
        with:
          cli: ${{ matrix.clojure }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            _build
          key: ${{ runner.os }}-erl${{ matrix.erlang }}-${{ hashFiles('rebar.lock') }}
          restore-keys: |
            ${{ runner.os }}-erl${{ matrix.erlang }}-
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-clj-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clj-
      - name: Lint & test
        run: |
          make test
